version: 2

builds:
- id: spin-plugin-azure
  main: ./cmd/azure/main.go
  binary: azure
  env:
   - CGO_ENABLED=0
  ldflags:
   - "-s -w -X github.com/spinkube/spin-plugin-azure/pkg/cmd.Version={{.Version}}"
  goos:
   - linux
   - darwin
   - windows
  goarch:
   - amd64
   - arm64 

archives:
- id: spin-plugin-azure
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
    - LICENSE

git:
  tag_filter: 'plugin/*' # Only consider tags starting with plugin/

release:
  tag_name: '{{ replace .Tag "plugin/" "" }}'
