name: Release it

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    permissions:
      # grant the github token the ability to modify release tags
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # fetch all history for goreleaser to work correctly
        # https://goreleaser.com/ci/actions/#workflow
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
        check-latest: true

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean ${{ github.ref == 'refs/heads/main' && '--snapshot' || '' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Release Plugin
      uses: rajatjindal/spin-plugin-releaser@fix-diff-tag-formats
      with:
        github_token: ${{ github.token }}
        upload_checksums: true
        template_file: contrib/spin-plugin.json.tmpl
        release_webhook_url: "https://spin-plugin-releaser-staging.fermyon.app"
